fer_todo_homepage:
    pattern:  /
    defaults: { _controller: FerTodoBundle:Task:index }

fer_todo_tareas:
    pattern:  /tareas
    defaults: { _controller: FerTodoBundle:Task:index }

fer_todo_tareas_lista:
    pattern:  /tareas/lista
    defaults: { _controller: FerTodoBundle:Task:list }
