<?php

namespace Fer\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Fer\TodoBundle\Entity\Task;
/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function remove(Task $task) {
        $this->getEntityManager()->remove($task);
        $this->getEntityManager()->flush();
    }

    public function save(Task $task) {
        if ($task->getId()) {
            $this->getEntityManager()->merge($task);
        } else {
            $this->getEntityManager()->persist($task);
        }
        $this->getEntityManager()->flush();
    }
}
