<?php
/**
 * Created by PhpStorm.
 * User: fernando
 * Date: 13/01/14
 * Time: 21:00
 */
namespace Fer\TodoBundle\Entity;

use Doctrine\DBAL\LockMode;


/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface TaskRepositoryInterface
{
    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id The identifier.
     * @param int $lockMode The lock mode.
     * @param int|null $lockVersion The lock version.
     *
     * @return object|null The entity instance or NULL if the entity can not be found.
     */
    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null);

    /**
     * Finds all entities in the repository.
     *
     * @return array The entities.
     */
    public function findAll();

    public function save(Task $task);

    public function remove(Task $task);
}