<?php

namespace Fer\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Fer\TodoBundle\Entity\Task;
/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function remove(Task $task) {
    }

    public function save(Task $task) {

    }
}
